const mongoose = require('mongoose');

/** Mirrors admin-portal TenantSettings for direct DB reads (e.g. public QR session). */
const tenantSettingsSchema = new mongoose.Schema(
  {
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Tenant',
      required: true,
      unique: true,
      index: true,
    },
    businessName: { type: String, default: '', trim: true },
    tagline: { type: String, default: '', trim: true },
    logoUrl: { type: String, default: '' },
    logoKey: { type: String, default: '' },
    faviconUrl: { type: String, default: '' },
    themePresetId: { type: String, default: 'default' },
    themePresetName: { type: String, default: 'Default / Base' },
    themeBaseColor: { type: String, default: '#0B1220' },
    bodyColor: { type: String, default: '#0B1220' },
    headerBarColor: { type: String, default: '#151F2E' },
    buttonColor: { type: String, default: '#E94560' },
    selectionHighlightColor: { type: String, default: '#2A3548' },
    hoverColor: { type: String, default: '#F06B82' },
    buttonTextColor: { type: String, default: '#F8FAFC' },
    headerBarTextColor: { type: String, default: '#F8FAFC' },
    bodyTextColor: { type: String, default: '#E2E8F0' },
    primaryColor: { type: String, default: '#0B1220' },
    accentColor: { type: String, default: '#e94560' },
    sidebarColor: { type: String, default: '#16213e' },
    textColor: { type: String, default: '#E2E8F0' },
    selectionTextColor: { type: String, default: '#ffffff' },
    address: { type: String, default: '' },
    phone: { type: String, default: '' },
    email: { type: String, default: '' },
    website: { type: String, default: '' },
    paymentMethods: { type: [String], default: ['cash'] },
    currency: { type: String, default: 'LKR' },
    currencySymbol: { type: String, default: 'Rs.' },
    timezone: { type: String, default: 'Asia/Colombo' },
    receiptHeader: { type: String, default: '' },
    receiptFooter: { type: String, default: 'Thank you for your visit!' },
    printReceiptByDefault: { type: Boolean, default: false },
    receiptPrintAtStatus: {
      type: String,
      enum: ['placement', 'preparing', 'ready', 'completed', 'none'],
      default: 'placement',
    },
    receiptPrintAtByOrderType: { type: mongoose.Schema.Types.Mixed, default: null },
    returnsEnabled: { type: Boolean, default: false },
    returnsRequireManagerApproval: { type: Boolean, default: true },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  },
  { timestamps: true },
);

module.exports = mongoose.model('TenantSettings', tenantSettingsSchema);
