export {
  LIMITS,
  PLACEHOLDERS,
  fieldAttrs,
  trim,
  validateEmail,
  validatePassword,
  validatePersonName,
  validateBusinessName,
  validateMobile,
  validateAddressLine,
  validateCity,
  validateRegion,
  validatePostalCode,
  validateRegistrationNumber,
  validateSubject,
  validateMessage,
  validateNotes,
  validateTagline,
  validatePhoneDisplay,
  validateWebsite,
  validateStoreName,
  validateStoreCode,
} from '@innovapos/form-validation/browser.js';
