export {
  LIMITS,
  PLACEHOLDERS,
  fieldAttrs,
  trim,
  validateEmail,
  validatePassword,
  validatePersonName,
  validateBusinessName,
  validateMobile,
  validateAddressLine,
  validateNotes,
  validateStoreName,
  validateStoreCode,
} from '@innovapos/form-validation/browser.js';
